[workspace]
members = [
    "voxbrix_client",
    "voxbrix_common",
    "voxbrix_protocol",
    "voxbrix_server",
    "local_channel"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
async-executor = "1.5"
rayon = "1.7"
blocking = "1.3"
futures-lite = "1.13"
async-io = "1.13"
flume = { version = "0.10", default-features = false, features = ["async"] }
serde = { version = "1.0", default-features = false, features = ["std", "derive"] } 
serde-big-array = "0.5"
k256 = { version = "0.13.0", features = ["ecdsa"] }
lz4_flex = { version = "0.10", default-features = false, features = ["checked-decode"] }
postcard = { version = "1.0", default-features = false, features = ["use-std"] }
arrayvec = { version = "0.7", default-features = false }
ron = "0.8"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
