[package]
name = "voxbrix_client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5"
futures-lite = "1.12"
blocking = "1.3"
flume = { version = "0.10", default-features = false, features = ["async"] }
async-io = "1.12"
rayon = "1.6"
async-fs = "1.6"
either = "1.8"
winit = "0.27"
wgpu = "0.14"
iced_winit = "0.6"
iced_wgpu = "0.7"
bytemuck = { version = "1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
anyhow = "1.0"
serde = { version = "1.0", default-features = false, features = ["std", "derive"] } 
voxbrix_protocol = { path = "../voxbrix_protocol", features = ["single", "client"] }
voxbrix_common = { path = "../voxbrix_common" }
local_channel = { path = "../local_channel" }
bitmask = "0.5"
arrayvec = { version = "0.7", default-features = false }
k256 = { version = "0.11.6", features = ["ecdsa"] }
argon2 = { version = "0.4.1", default-features = false, features = ["alloc"] }
log = "0.4"
env_logger = "0.9"
