[package]
name = "voxbrix_client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5"
futures-lite = "1.12"
blocking = "1.2"
flume = "0.10"
async-io = "1.8"
rayon = "1.6"
async-fs = "1.6"
either = "1.8"
winit = "0.27"
wgpu = "0.14"
bytemuck = { version = "1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
anyhow = "1.0"
serde = { version = "1.0", default-features = false, features = ["std", "derive"] } 
voxbrix_protocol = { path = "../voxbrix_protocol", features = ["single", "client"] }
voxbrix_common = { path = "../voxbrix_common" }
local-channel = "0.1"
bitmask = "0.5"
arrayvec = { version = "0.7", default-features = false }
ron = "0.8"
log = "0.4"
env_logger = "0.9"
