[package]
name = "remove_block"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[workspace]

[profile.release]
lto = true
strip = true
opt-level = 's'
codegen-units = 1

[dependencies]
server_loop_api = { path = "../../server_loop_api" }
