[package]
name = "voxbrix_protocol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#postcard = "1.0"
#serde = "1.0"
integer-encoding = "3.0"
async-io = "1.9"
futures-lite = "1.12"
local-channel = "0.1"
log = "0.4"

[dev-dependencies]
async-executor = "1.4"
