[package]
name = "voxbrix_ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
voxbrix_ecs_derive = { version = "0.1.0", path = "voxbrix_ecs_derive", optional = true }

[features]
default = [ "derive" ]
derive = [ "voxbrix_ecs_derive" ]
