[package]
name = "voxbrix_server"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5"
blocking = "1.2"
futures-lite = "1.12"
async-io = "1.10"
voxbrix_protocol = { path = "../voxbrix_protocol", features = ["single", "server"] }
voxbrix_common = { path = "../voxbrix_common" }
redb = "0.10"
flume = "0.10"
serde = "1.0"
#postcard = "1.0"
local-channel = "0.1"
arrayvec = { version = "0.7", default-features = false }
anyhow = "1.0"
log = "0.4"
env_logger = "0.9"
